name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build-test:
        runs-on: Ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - run: dotnet restore
        - run: dotnet build --no-restore --configuration Release
        - run: dotnet test --no-build --configuration Release --verbosity normal

        
        - name: Built Docker Image
          run: docker build -t cicddemo1 .

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Push to Docker Hub
          run: |
            docker tag cicddemo1 ${{ secrets.DOCKERHUB_USERNAME }}/cicddemo1:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicddemo1:latest
