name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build-test:
        runs-on: Ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - run: dotnet restore
        - run: dotnet build --no-restore --configuration Release
        - run: dotnet test --no-build --configuration Release --verbosity normal